# -*- coding: utf-8 -*-
"""ChatGPT_Asistente_e_commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9wgi9KXyejlAUYYO3RgSnzVVInQ8P9J

# **ASISTENTE VIRTUAL E-COMMERCE**
"""

"""from google.colab import drive
drive.mount('/content/drive')
"""


"""## **1. Instalar librerías necesarias**"""

#!pip install langchain-google-genai langchain-chroma
#!pip install langchain-huggingface sentence-transformers
#!pip install openpyxl pymupdf langchain gTTS pygame
#!pip install langchain-community pypdf
#!pip install -qU langchain langchain-community pypdf
#!pip install python-telegram-bot
#!pip install openai
#!pip install langchain-openai

"""## **2. Agregar documentos al asistente**"""

# Lista de documentos
documents = []
ids = []

# Agregar PDFs
from langchain_community.document_loaders import PyPDFDirectoryLoader


carpeta_archivos = "./mis_archivos"
loader = PyPDFDirectoryLoader(carpeta_archivos)
archivos = loader.load()

print(f"Páginas cargadas: {len(archivos)}")

# Dividir datos en trozos (chunks)
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

porcionador = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
trozos = porcionador.split_documents(archivos)
print(f"Cantidad de trozos: {len(trozos)}")

# Agregamos los trozos a los documentos del asistente
documents = trozos
ids = [ str(i) for i in range( len(documents) ) ]

# Agregar archivos Excel, CSV
import pandas as pd

nombre_archivo = "./mis_archivos/Copia de Tabla productos.xlsx"
if nombre_archivo != "":
    tabla = pd.read_excel(nombre_archivo)

    id = len(ids)
    for i, fila in tabla.iterrows():

        # Configurar los nombres de las columnas
        doc = Document(
            page_content = f"""
                Nombre:             {fila['Nombre']}
                Categoría:          {fila['Categoría']}
                Calificación:       {fila['Calificación']}
                Unidades Vendidas:  {fila['Unidades Vendidas']}
                En Tendencia:       {fila['En Tendencia']}
                Valor (USD):        {fila['Valor (USD)']}
                Opiniones Buenas:   {fila['Opiniones Buenas']}
                Opiniones Malas:    {fila['Opiniones Malas']}
                """,

            # Configurar columnas con metadatos
            metadata = {
                "En Tendencia":     fila["En Tendencia"],
                "Opiniones Buenas": fila["Opiniones Buenas"],
                "Opiniones Malas":  fila["Opiniones Malas"]
            },
            id = str(id)
        )

        # Agregamos los documentos al asistente virtual
        documents.append(doc)
        ids.append(str(id))
        id += 1

"""## **3. Crear modelo de incrustación**"""

from langchain_huggingface import HuggingFaceEmbeddings

modelo_incrustacion = HuggingFaceEmbeddings(model_name="intfloat/multilingual-e5-large")

# Crear carpeta para la base de datos vectorial
from langchain_chroma import Chroma

base_datos = './base_datos_e5'

base_datos_vectorial = Chroma.from_documents(
    ids = ids,
    documents = documents,
    embedding = modelo_incrustacion,
    persist_directory = base_datos
)

recuperador = base_datos_vectorial.as_retriever()

"""## **4. Conexión con LLM ChatGPT**
* **LLM**: Large Language Model (Modelo de lenguaje Extendido)

"""

# Crear modelo de ChatGpt

from langchain_openai import ChatOpenAI

import openai
# Llave de acceso
API_KEY  = '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'

modelo = ChatOpenAI(
    model="gpt-4.1",
    temperature=0,
    api_key=API_KEY
)

# Configurar modelo de Gemini
from langchain_core.prompts import ChatPromptTemplate

plantilla = """
Eres un asistente virtual de comercio electrónico llamado "PACO-POP".
Debes ayudar a vender los productos de la empresa "ESTAF-A WEB" que
se dedica a la venta de productos para el hogar y tecnología.
Todos los precios muestralos en peso colombiano.
Debes dar respuetas cortas y precisas con tonalidad alegre y cordial.
No incluir emojis, emoticonos ni asteriscos en la respuesta.

Si el usuario muestra interés en un producto, ofrece la información de manera clara y amigable (nombre, precio y características si aplica) y pregúntale si desea agregarlo al carrito. Si responde afirmativamente con palabras como “si”, “ok”, “dale”, “añadelo” o similares, agrega el producto directamente sin volver a preguntar y confirma que fue añadido.

Después de cada adición, muestra un resumen actualizado y ordenado del carrito, indicando nombre del producto, cantidad, precio individual y total acumulado.

Si el usuario solicita información sobre otros productos mientras compra, respóndele con las opciones disponibles sin interrumpir su flujo de compra. Si luego dice “sí” o cualquier respuesta afirmativa, añade automáticamente el producto indicado al carrito.

Cuando el usuario pregunte por el total o indique que quiere finalizar la compra, muestra un resumen claro y amigable de todos los productos en el carrito con sus precios y el total a pagar. Luego pregúntale si desea confirmar la compra.

Si responde afirmativamente, confirma la transacción y muestra un mensaje final cálido y comercial, por ejemplo:
“¡Excelente! Tu compra ha sido confirmada con éxito. Muchas gracias por tu preferencia. Tu pedido ha sido guardado y pronto estará en camino.”

En todo momento:

Usa un tono amable, entusiasta y cercano.

Interpreta respuestas afirmativas de forma flexible (no obligues al usuario a repetir frases exactas).

No repitas preguntas innecesarias si ya fue clara la intención del usuario.

Permite al usuario seguir agregando productos, consultar precios o finalizar cuando desee.

Al final, agradece siempre su compra.



pregunta {pregunta}
contexto {contexto}
respuesta {respuesta}
"""

"""## **5. Probar el asistente**

## **6. Conectar el asistente virtual con Telegram**
"""

# Función respuesta

prompt = ChatPromptTemplate.from_template( plantilla )
cadena = prompt | modelo
contexto = ''

def respuesta_ia(pregunta):
    global contexto
    respuesta = recuperador.invoke( pregunta )
    mostrar = cadena.invoke({
        'contexto': contexto,
        'pregunta': pregunta,
        'respuesta': respuesta
    })

    contexto += f"\nUsuario: {pregunta}\nBot: {respuesta}"
    return mostrar.content

import logging
import asyncio
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes

logging.basicConfig(level=logging.INFO)
TOKEN = "8210771410:AAGe4pc_No5NK_vD42nPpQltUs8AQlB5EC0"

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("¡Hola! Soy PACO-POP, tu asistente de compras 🛒")

async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_text = update.message.text


    mostrar = respuesta_ia(user_text)
    await update.message.reply_text(mostrar)

async def main():
    app = ApplicationBuilder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, echo))
    print("Bot en marcha… Ctrl+C para salir")
    await app.run_polling()

try:
    asyncio.run(main())
except RuntimeError:
    import nest_asyncio
    nest_asyncio.apply()
    asyncio.get_event_loop().run_until_complete(main())